### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fabaff** [Florian7843/pykostalpiko#1]
There is a version mismatch present between GitHub and PyPI:

- GitHub: https://github.com/Florian7843/pykostalpiko/releases/tag/v1.1.1-1
- PyPI: https://pypi.org/project/pykostalpiko/1.1.1.post1/

In the source tarball published on PyPI is the version in `setup.py`: `VERSION = "1.1.1-1"`

**Comment by Florian7843** [comment]
Doesn't PyPI auto change the "-" to the "post"?
Is that not supposed to happen? 

Anyway, the repo is now a newer version, so it shouldn't really matter anymore.
